### ISSUE TITLE
Incompatibility with guzzlehttp/guzzle 7.4.2

### ISSUE THREAD

**Issue by georgeduta** [subscribepro/subscribepro-php#43]

**Comment by cyildirim** [comment]
i am having the same issue can you create tag guzzle-test ? It impacts magento 2.4.4 upgrade @graysonblanchard

**Comment by DmitryFurs** [comment]
Are there any updates on this? We can't upgrade to version 2.4.4

**Comment by adriansanta** [comment]
@garthbrantley @graysonblanchard

FYI, there are also security implications of not upgrading the dependency to guzzlehttp/guzzle, see below:

GitHub Dependabot suggests a minimum of "guzzlehttp/guzzle": "6.5.8", ideally over 7.4.5, anything older is subject to 6 high severity security vulnerabilities:

- Change in port should be considered a change in origin - https://github.com/advisories/GHSA-q559-8m2m-g699
- CURLOPT_HTTPAUTH option not cleared on change of origin - https://github.com/advisories/GHSA-25mq-v84q-4j7r
- Failure to strip the Cookie header on change in host or HTTP downgrade - https://github.com/advisories/GHSA-f2wf-25xc-69c9
- Fix failure to strip Authorization header on HTTP downgrade - https://github.com/advisories/GHSA-w248-ffj2-4v5q 
- Cross-domain cookie leakage in Guzzle - https://github.com/advisories/GHSA-cwmx-hcrq-mhc3
- HTTP Proxy header vulnerability - https://github.com/advisories/GHSA-m6ch-gg5f-wxx3
